'use client';
import {useEffect,useRef,useState,useId,type CSSProperties} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,ArrowLeft,BookOpen,Network,LayoutGrid,Search,Maximize2,Minimize2,RotateCcw,Pause,Play,Move,Compass,GitCompareArrows,ChevronRight,X,Expand,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import ModelStage,{MiniModel} from '@/components/model-stage';
import {entries,categories,findEntry,relationships,type Entry} from '@/lib/atlas-data';

type View='explore'|'atlas'|'connections'|'compare'|'sources'|'entry';
const nav=[{href:'/',label:'空间探索',view:'explore',icon:Compass},{href:'/atlas',label:'主题图鉴',view:'atlas',icon:LayoutGrid},{href:'/connections',label:'关系图谱',view:'connections',icon:Network},{href:'/compare',label:'对照阅读',view:'compare',icon:GitCompareArrows},{href:'/sources',label:'典籍索引',view:'sources',icon:BookOpen}];
function Ornament(){return <svg viewBox="0 0 40 40" className="brand-mark" aria-hidden="true"><path d="M20 2 25 14 38 20 25 25 20 38 14 25 2 20 14 14Z" fill="none" stroke="currentColor" strokeWidth="1.3"/><circle cx="20" cy="20" r="9" fill="none" stroke="currentColor"/><path d="M20 9v22M9 20h22" stroke="currentColor" strokeWidth=".7"/></svg>}
function Header({view}:{view:View}){return <header className="site-header"><Link href="/" className="brand"><Ornament/><span><strong className="serif">她象</strong><small>HER COSMOS</small></span></Link><nav aria-label="主要导航">{nav.map(n=><Link className={(view===n.view||(view==='entry'&&n.view==='explore'))?'active':''} href={n.href} key={n.href}><n.icon size={16}/><span>{n.label}</span></Link>)}</nav><span className="header-note">女性 · 古典文化 · 新的观看</span></header>}
function SourceLink({entry}:{entry:Entry}){return <a className="source-link" href={entry.url} target="_blank" rel="noreferrer">{entry.source}<ArrowUpRight size={15}/></a>}
function Footer(){return <footer><span className="serif">她象 · 万物生辉</span><p>古典有来处，理解有新的可能。</p><Link href="/sources">原典与编选说明 <ArrowUpRight size={14}/></Link></footer>}
function DetailText({entry}:{entry:Entry}){return <div className="reading-content"><Tabs defaultValue="context" key={entry.id}><TabsList className="reading-tabs"><TabsTrigger value="context">原典语境</TabsTrigger><TabsTrigger value="today">今天怎么看</TabsTrigger></TabsList><TabsContent value="context"><p>{entry.context}</p></TabsContent><TabsContent value="today"><p>{entry.reading}</p></TabsContent></Tabs></div>}
function DetailPanel({entry,compact=false}:{entry:Entry;compact?:boolean}){return <aside className="detail-panel" key={entry.id}><div className="entry-index"><span>{entry.category}</span><span>{String(entries.indexOf(entry)+1).padStart(2,'0')} / 12</span></div><div className="entry-heading"><h2 className="serif">{entry.name}</h2><span className="entry-seal">{entry.symbol}</span></div><p className="entry-en">{entry.english}</p><div className="theme-label"><i style={{background:entry.colors[0]}}/>{entry.theme}</div><p className="entry-intro">{entry.intro}</p><blockquote className="serif">{entry.quote}</blockquote><SourceLink entry={entry}/>{compact?<><div className="related-edges"><h3>与它相连</h3>{relationships.filter(r=>r.a===entry.id||r.b===entry.id).map(r=>{const e=findEntry(r.a===entry.id?r.b:r.a)!;return <Link key={e.id} href={'/entry/'+e.id}><span>{e.name}<small>{r.label}</small></span><ArrowUpRight size={16}/></Link>})}</div><Link className="full-read" href={'/entry/'+entry.id}>进入专题 <ArrowRight size={16}/></Link></>:<><DetailText entry={entry}/><Link className="full-read" href={'/entry/'+entry.id}>阅读全文与关联 <ArrowRight size={16}/></Link></>}</aside>}
function Stage({entry,graph=false,onSelect,detail=false}:{entry:Entry;graph?:boolean;onSelect?:(id:string)=>void;detail?:boolean}){
 const [playing,setPlaying]=useState(true),[amount,setAmount]=useState(56),[pulse,setPulse]=useState(0),[reset,setReset]=useState(0),[full,setFull]=useState(false);const stage=useRef<HTMLDivElement>(null);const rangeId=useId();
 useEffect(()=>{const query=window.matchMedia('(prefers-reduced-motion: reduce)');setPlaying(!query.matches);const fn=()=>setPlaying(!query.matches);query.addEventListener('change',fn);return()=>query.removeEventListener('change',fn)},[]);
 useEffect(()=>{setAmount(56);setPulse(0)},[entry.id]);
 useEffect(()=>{const fn=()=>setFull(document.fullscreenElement===stage.current);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn)},[]);
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(stage.current?.requestFullscreen)await stage.current.requestFullscreen();else setFull(!full);}catch{setFull(!full);}}
 useEffect(()=>{if(!full)return;const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setFull(false)};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[full]);
 function act(){setPulse(v=>v+1);if(!['water','tide'].includes(entry.model))setAmount(v=>v>75?18:100);}
 return <section ref={stage} className={`visual-stage ${full?'expanded':''}`} style={{'--model-accent':entry.colors[0]} as CSSProperties}>
  <div className="stage-top"><span className="scene-eyebrow">{graph?'CONNECTIONS / 关系探索':'LIVING FORM / 意象空间'}</span><div><button className="icon-button" aria-label="重置视角" title="重置视角" onClick={()=>{setReset(v=>v+1);setAmount(56);}}><RotateCcw size={17}/></button><button className="icon-button" aria-label={full?'退出全屏':'全屏展示'} title="全屏展示" onClick={fullscreen}>{full?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button></div></div>
  <div className="scene-heading"><span className="serif">{graph?'让知识，相互照见。':entry.subtitle}</span><small>{graph?'点击节点，展开它的关系':`${entry.name} · ${entry.theme}`}</small></div>
  <ModelStage entry={entry} playing={playing} amount={amount} pulse={pulse} reset={reset} graph={graph} onSelect={onSelect}/>
  {!graph&&<div className="model-action"><button onClick={act}><span className="action-star">✦</span>{entry.action}<ArrowRight size={16}/></button><span>意象演绎</span></div>}
  {graph&&<div className="graph-legend"><span><i/>文本关联</span><span><i/>主题对读</span></div>}
  <div className="stage-controls"><span className="drag-hint"><Move size={15}/>拖动旋转 · 滚轮缩放</span>{!graph&&<div className="range-control"><label id={rangeId}>{entry.slider}</label><Slider aria-labelledby={rangeId} value={[amount]} min={0} max={100} step={1} onValueChange={v=>setAmount(v[0])}/><span>{amount}%</span></div>}<button className="play-button" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={14}/>:<Play size={14}/>}<span>{playing?'暂停动态':'播放动态'}</span></button></div>
  {detail&&<p className="instruction">{entry.interaction}</p>}
 </section>;
}
function Card({entry,index,selected,onSelect}:{entry:Entry;index:number;selected?:boolean;onSelect?:(id:string)=>void}){const contents=<><div className="card-meta"><span>{String(index+1).padStart(2,'0')}</span><span>{entry.category}</span></div><div className="card-model"><MiniModel entry={entry}/></div><div className="card-info"><div><h3 className="serif">{entry.name}</h3><p>{entry.theme}</p></div><span className="card-arrow"><ArrowUpRight size={18}/></span></div></>;const style={'--card-color':entry.colors[0],'--card-color2':entry.colors[1]} as CSSProperties;return onSelect?<button aria-pressed={selected} className={`topic-card ${selected?'selected':''}`} style={style} onClick={()=>onSelect(entry.id)}>{contents}</button>:<Link className="topic-card" style={style} href={'/entry/'+entry.id}>{contents}</Link>}
function TopicGrid({selected,onSelect,withSearch=false}:{selected?:string;onSelect?:(id:string)=>void;withSearch?:boolean}){const [category,setCategory]=useState('全部'),[query,setQuery]=useState('');const filtered=entries.filter(e=>(category==='全部'||e.category===category)&&[e.name,e.theme,e.source,e.intro].join(' ').includes(query.trim()));return <section className="topics-section"><div className="section-heading"><div><span className="eyebrow">THE COLLECTION</span><h2 className="serif">十二象，各自生辉。</h2></div><div className="collection-tools">{withSearch&&<label className="search-box"><Search size={16}/><input aria-label="搜索人物、意象或典籍" placeholder="搜索人物、意象、典籍" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={15}/></button>}</label>}<Tabs value={category} onValueChange={setCategory}><TabsList className="category-tabs">{categories.map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs></div></div><div className="topic-grid">{filtered.map(e=><Card key={e.id} entry={e} index={entries.indexOf(e)} selected={selected===e.id} onSelect={onSelect}/>)}</div>{filtered.length===0&&<div className="empty"><Search size={28}/><p>没有找到相关条目</p><button onClick={()=>{setQuery('');setCategory('全部')}}>查看全部十二象</button></div>}</section>}
function Explore({view,initialId}:{view:View;initialId?:string}){const [id,setId]=useState(initialId??'nuwa');const entry=findEntry(id)??entries[0];const graph=view==='connections';const select=(v:string)=>{setId(v)};return <><div className="page-intro"><div><div className="eyebrow">{graph?'A CONSTELLATION OF IDEAS':'AN ATLAS OF FEMININE IMAGINATION'}</div><h1 className="serif">{graph?<>在关联中，<em>重新理解。</em></>:<>她的万象，<em>生生不息。</em></>}</h1></div><p>{graph?'循着人物、文本与意象，发现另一条阅读路径。':'在神话、易象与哲思之间，探索女性的多重想象。'}<br/><span>12 个专题 · 3 重视角 · 自由探索</span></p></div><div className="explore-layout"><Stage entry={entry} graph={graph} onSelect={select}/><DetailPanel entry={entry} compact={graph}/></div>{graph?<section className="node-directory"><h2 className="serif">选择一个节点</h2><div>{entries.map(e=><button className={id===e.id?'selected':''} onClick={()=>select(e.id)} key={e.id}>{e.name}</button>)}</div><p>实线表示可核查的文本联系；虚线表示本项目提出的主题对读，不代表历史影响关系。</p></section>:<TopicGrid selected={entry.id} onSelect={v=>{select(v);document.querySelector('.explore-layout')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}}/>}</>}
function EntryPage({id}:{id:string}){const entry=findEntry(id)!;return <><div className="breadcrumb"><Link href="/atlas">主题图鉴</Link><ChevronRight size={13}/><span>{entry.category}</span><ChevronRight size={13}/><span>{entry.name}</span></div><div className="entry-title-row"><div><span className="eyebrow">{entry.english}</span><h1 className="serif">{entry.name}<small>{entry.theme}</small></h1></div><Link className="text-link" href="/connections">在图谱中继续探索 <Network size={16}/></Link></div><div className="entry-layout"><Stage entry={entry} detail/><article className="long-reading"><span className="eyebrow">FROM THE TEXT</span><blockquote className="serif">{entry.quote}</blockquote><SourceLink entry={entry}/><h2 className="serif">原典中的她与它</h2><p>{entry.context}</p><h2 className="serif">换一种目光</h2><p>{entry.reading}</p><div className="question-box"><span>留给你的问题</span><h3 className="serif">{entry.question}</h3></div><p className="model-note">模型为依据文本意象进行的现代视觉创作。人物、卦象与几何形式之间不主张数学对应关系。</p></article></div><section className="related-section"><div className="section-heading"><h2 className="serif">沿着另一条线索</h2><Link href="/atlas">全部专题 <ArrowRight size={16}/></Link></div><div className="related-grid">{entry.related.map(id=>findEntry(id)!).map(e=><Card key={e.id} entry={e} index={entries.indexOf(e)}/>)}</div></section></>}
function Compare(){const [left,setLeft]=useState('nuwa'),[right,setRight]=useState('jingwei');const a=findEntry(left)!,b=findEntry(right)!;const [mode,setMode]=useState('topics');return <><div className="page-intro"><div><span className="eyebrow">READ SIDE BY SIDE</span><h1 className="serif">不同的她，<em>相互照见。</em></h1></div><p>保留差异，让理解发生。</p></div><Tabs value={mode} onValueChange={setMode}><TabsList className="compare-tabs"><TabsTrigger value="topics">专题对读</TabsTrigger><TabsTrigger value="history">西王母 · 多重形象</TabsTrigger></TabsList><TabsContent value="topics"><div className="comparison-grid">{[{e:a,id:left,set:setLeft},{e:b,id:right,set:setRight}].map(({e,id,set},i)=><article className="compare-column" key={i}><Select value={id} onValueChange={set}><SelectTrigger aria-label={i?'选择右侧专题':'选择左侧专题'} className="entry-select"><SelectValue/></SelectTrigger><SelectContent>{entries.map(e=><SelectItem key={e.id} value={e.id}>{e.name} · {e.theme}</SelectItem>)}</SelectContent></Select><Stage entry={e}/><div className="compare-reading"><h2 className="serif">{e.name}</h2><blockquote>{e.quote}</blockquote><SourceLink entry={e}/><p>{e.reading}</p><div className="question-box"><span>思考</span><h3 className="serif">{e.question}</h3></div></div></article>)}</div><p className="comparison-note">{left===right?'你正在从两种操作状态观看同一个专题，也可以更换其中一个进行对读。':'并置是一种阅读方法，不表示两者存在历史传承关系。'}</p></TabsContent><TabsContent value="history"><History/></TabsContent></Tabs></>}
function History(){const [index,setIndex]=useState(0);const texts=[{label:'《山海经》',title:'异质的威力',quote:'豹尾虎齿而善啸，蓬发戴胜。',body:'《西山经》中的西王母居于玉山。身体的异质性和强烈的声音，共同构成这段记述的神力形象。',url:'https://ctext.org/shan-hai-jing/xi-shan-jing/zh'},{label:'《淮南子》',title:'不死之药',quote:'羿请不死之药于西王母。',body:'《览冥训》把西王母放入不死之药与奔月的叙事。此处的关注点转向长生资源，以及它与其他人物的关系。',url:'https://ctext.org/huainanzi/lan-ming-xun/zhs'},{label:'汉代图像 · 故宫解读',title:'长生与秩序',quote:'从文本走向图像的世界。',body:'故宫“开天辟地”展览介绍汉代宇宙图像中的西王母，将她与昆仑、死后世界的秩序及长生想象联系起来。这是博物馆对图像语境的解释。',url:'https://theme.npm.edu.tw/GodsAmongUs114/page-2'}];const t=texts[index];return <div className="history-layout"><div><Stage entry={{...entries[1],id:`xiwangmu-view-${index}`,model:["mountain","portal","balance"][index],subtitle:["异质神力，层层显现。","不死之药，连接诸神。","环绕昆仑，长生与秩序。"][index]}}/><div className="history-steps">{texts.map((t,i)=><button key={t.label} className={i===index?'active':''} onClick={()=>setIndex(i)}><small>0{i+1}</small>{t.label}</button>)}</div></div><article className="long-reading" aria-live="polite"><span className="eyebrow">{t.label}</span><h2 className="serif">{t.title}</h2><blockquote className="serif">{t.quote}</blockquote><p>{t.body}</p><a className="source-link" href={t.url} target="_blank" rel="noreferrer">查看对应资料<ArrowUpRight size={16}/></a><div className="question-box"><span>阅读提示</span><p>这些材料展现不同语境，不是一个形象必然取代另一个形象的线性进化。</p></div></article></div>}
function Sources(){const [query,setQuery]=useState('');const filtered=entries.filter(e=>[e.name,e.source,e.quote].join('').includes(query.trim()));return <><div className="page-intro"><div><span className="eyebrow">READ THE ORIGINALS</span><h1 className="serif">每一种想象，<em>都有来处。</em></h1></div><p>从这里回到文本，形成你自己的理解。</p></div><div className="source-intro"><div><span>01 / 原典</span><p>摘录标明篇章，保留原文语境。</p></div><div><span>02 / 解读</span><p>现代问题与解释，单独说明。</p></div><div><span>03 / 意象</span><p>动态模型为本项目的视觉创作。</p></div></div><div className="source-toolbar"><h2 className="serif">典籍与条目</h2><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索典籍" placeholder="搜索典籍或人物"/></label></div><div className="source-list">{filtered.map((e,i)=><article key={e.id}><span className="source-number">{String(i+1).padStart(2,'0')}</span><div><h3>{e.source}</h3><p className="serif">“{e.quote}”</p><Link href={'/entry/'+e.id}>{e.name} · {e.theme}<ArrowRight size={13}/></Link></div><a href={e.url} target="_blank" rel="noreferrer" aria-label={`打开${e.source}原文`}><ExternalLink size={18}/><span>查看原文</span></a></article>)}{!filtered.length&&<p className="empty">没有匹配的典籍，试试其他关键词。</p>}</div><article className="editorial-note"><h2 className="serif">编选说明</h2><p>“她象”关注中国古典文化中的女性形象、性别象征与相关哲学表达。神话、文学、易学和老子哲学各有语境；本项目通过并置来阅读，不把它们合并为一套统一学说。称谓、人物身份与文本解释可能存在不同版本，本项目不将一种解读当作唯一答案。</p><p>阴阳、母女与雌雄等古代分类，是被研究的文化材料，不是现实女性的性格分类、能力判断或行为规范。现代生理、心理与医疗知识也不能由这些象征推出。本项目不提供占卜、算命或医疗建议。</p><p>原文摘录以公开古籍为依据，正文采用简体转写。部分资料页可能需要访问验证。关系图中的“主题对读”由本项目编选，不主张史实上的影响关系。花园插画为 AI 辅助原创意象，不作为历史文物或场景的证据。</p></article></>}
export default function Atlas({view='explore',initialId}:{view?:View;initialId?:string}){return <div className="site-shell"><a className="skip-link" href="#main">跳到主要内容</a><Header view={view}/><main id="main">{view==='explore'||view==='connections'?<Explore view={view}/>:view==='atlas'?<><div className="collection-banner" style={{backgroundImage:`url('${process.env.NEXT_PUBLIC_BASE_PATH??''}/garden.png')`}}><div><span className="eyebrow">THE LIVING ARCHIVE</span><h1 className="serif">万物有形，<br/><em>智慧生长。</em></h1><p>十二个入口，通往神话、易象与哲思。</p></div></div><TopicGrid withSearch/></>:view==='entry'?<EntryPage id={initialId!}/>:view==='compare'?<Compare/>:<Sources/>}</main><Footer/></div>}
