export type Entry = {
 id:string; name:string; english:string; category:'神话人物'|'易象'|'哲思'; symbol:string;
 theme:string; subtitle:string; intro:string; quote:string; source:string; url:string;
 context:string; reading:string; question:string; model:string; colors:string[];
 action:string; slider:string; interaction:string; related:string[];
};
export const entries: Entry[] = [
 {id:'nuwa',name:'女娲',english:'NÜWA',category:'神话人物',symbol:'娲',theme:'创造 · 修复',subtitle:'把破碎，重新织成天空。',intro:'从五色石到重立四极，女娲的行动连接着创造、修复与世界秩序。',quote:'于是女娲炼五色石以补苍天，断鳌足以立四极。',source:'《淮南子·览冥训》',url:'https://ctext.org/huainanzi/lan-ming-xun/zhs',context:'《览冥训》描绘了天地失序、洪水与猛兽危及生民的情境。女娲补天、立极、止水，使世界重新安定。这段叙事的重点，是对灾难的回应和秩序的恢复。',reading:'今天可以从这段神话讨论女性作为行动者与创造者的形象。修复也可以是一种创造：重新组织已经破裂的关系与空间。但“女性有义务修补一切”不是我们从神话中推出的要求。',question:'创造一个世界，与修复一个世界，有什么不同？',model:'sky',colors:['#17cbb0','#fa69a5','#8276f2','#f2c657','#4baeed'],action:'合拢天穹',slider:'天穹完整度',interaction:'拖动滑块，让五色曲面从离散到聚合；拖拽模型可从不同角度观看接缝。',related:['jingwei','kun','xuanpin']},
 {id:'xiwangmu',name:'西王母',english:'QUEEN MOTHER OF THE WEST',category:'神话人物',symbol:'西',theme:'威力 · 秩序',subtitle:'在昆仑，重读力量的形状。',intro:'不同文本与图像中的西王母，打开了女性神力、威严与长生想象的多重侧面。',quote:'西王母其状如人，豹尾虎齿而善啸，蓬发戴胜。',source:'《山海经·西山经》',url:'https://ctext.org/shan-hai-jing/xi-shan-jing/zh',context:'《西山经》记述西王母居于玉山，并以豹尾、虎齿、善啸等特征表现她的异质神力。《淮南子》又把她与不死之药联系起来。不同材料保留了不同面向，不必拼成一条简单的进化线。',reading:'这里可以讨论：我们为什么习惯把女性神明想象得温柔？威严、危险、守护与权力能否同时存在？现代观看可以保留形象的复杂性，而不急着把她归为某一种女性榜样。',question:'当一位女神不再被要求温柔，你会如何理解她？',model:'mountain',colors:['#12a8b1','#705cea','#e5b949','#ec73a8','#5ee6ce'],action:'展开层境',slider:'空间层次',interaction:'展开层叠曲面与环轨，观察外部威严与内部秩序的视觉对照。',related:['change','nuwa','li']},
 {id:'change',name:'嫦娥',english:'CHANG’E',category:'神话人物',symbol:'月',theme:'月亮 · 距离',subtitle:'飞向月亮，也走进叙事。',intro:'奔月的故事在不同讲述中改变含义。先读文本，再观察是谁在评价她的选择。',quote:'譬若羿请不死之药于西王母，姮娥窃以奔月。',source:'《淮南子·览冥训》',url:'https://ctext.org/text.pl?if=gb&node=3128&show=parallel',context:'这段文本使用“姮娥”这一写法，并在讨论来源与延续的论述中引入奔月故事。“窃”是原文的叙事措辞。我们在这里呈现文本的判断，也提醒读者区分故事人物与讲述者的视角。',reading:'月亮可以成为讨论距离、孤独和自主选择的入口。但把奔月直接解释为现代女性解放，是今天的再创作，不能倒写成古人的唯一原意。',question:'同一个离开的动作，为什么会被讲成不同的故事？',model:'moon',colors:['#8a86f2','#b7e8ec','#edabcb','#e6c566','#4bb1cc'],action:'切换月相',slider:'光照角度',interaction:'改变光照方向，观察同一个球面如何呈现不同的明暗；它是视觉示意，不是历法预测。',related:['xiwangmu','luoshen','dui']},
 {id:'jingwei',name:'精卫',english:'JINGWEI',category:'神话人物',symbol:'羽',theme:'意志 · 持续',subtitle:'微小的行动，也有方向。',intro:'女娃溺海后化为精卫，衔取木石填海。重复的行动，构成故事最鲜明的节奏。',quote:'常衔西山之木石，以堙于东海。',source:'《山海经·北山经》',url:'https://ctext.org/text.pl?if=gb&node=83673&show=parallel',context:'《北山经》将精卫叙述为炎帝少女女娃所化的鸟，记载她游东海、溺而不返，继而以木石填海。此处的“女娃”与补天的“女娲”不是同一个名字或故事。',reading:'持续的行动可以让人想到意志，也可以让人追问代价、失去与不愿放弃。我们把多种问题并置，不将忍耐和无休止付出规定为女性美德。',question:'坚持的意义，必须由最终结果来证明吗？',model:'tide',colors:['#fa7796','#f1c05b','#25c4bd','#729bef','#b695e7'],action:'投入一石',slider:'潮汐幅度',interaction:'投入一颗光石，看涟漪扩散；每次行动会留下一个新的环形标记。',related:['nuwa','dui','shouci']},
 {id:'luoshen',name:'洛神',english:'SPIRIT OF THE LUO RIVER',category:'神话人物',symbol:'洛',theme:'凝视 · 想象',subtitle:'美的背后，是谁的目光？',intro:'流动的身姿与难以抵达的相遇，让洛神成为文学想象中极具张力的形象。',quote:'翩若惊鸿，婉若游龙。',source:'曹植《洛神赋》',url:'https://ctext.org/wiki.pl?chapter=943054&if=gb',context:'《洛神赋》通过叙述者的目光铺陈洛水女神的容貌、姿态与相遇。作品具有文学虚构的性质；这里讨论的是赋中的形象，不把它当作真实女性的传记。',reading:'当代阅读可以一边欣赏语言的美，一边追问被观看者有没有自己的声音。切换观察角度，也是一种理解叙述位置的练习。',question:'一个被描写得极美的人，是否也被充分理解？',model:'ribbon',colors:['#f28bc8','#7c9de6','#3ac9c1','#efd18e','#aa6bdd'],action:'舒展流线',slider:'流线展开度',interaction:'改变丝带的舒展程度，旋转观看重叠与遮蔽，思考视角如何改变你看到的形状。',related:['xiang','change','xun']},
 {id:'xiang',name:'湘夫人',english:'LADY OF THE XIANG',category:'神话人物',symbol:'湘',theme:'水域 · 相望',subtitle:'在香草与水波之间相望。',intro:'《九歌》中的水域、香草和等待，编织出人与神相遇的诗性空间。',quote:'袅袅兮秋风，洞庭波兮木叶下。',source:'《楚辞·九歌·湘夫人》',url:'https://ctext.org/chu-ci/xiang-fu-ren/zhs',context:'《湘夫人》呈现水域、芳草、筑室和期会等意象。篇中的说话者、神灵身份与祭祀背景有不同解释；这个专题聚焦可以从文本直接看到的空间与情感线索。',reading:'在一段关于等待的叙述中，可以同时看见美、期待与不确定。我们尝试把“她的空间”从人物外貌扩展到水域、声音与环境，而不替古人确定唯一的心理答案。',question:'如果不描绘容貌，你会怎样让一个人物在场？',model:'water',colors:['#28c9aa','#87b9ef','#f3a0c6','#d6bd73','#8580cf'],action:'唤起水纹',slider:'波纹起伏',interaction:'触发水纹，让透明曲面逐层回应；改变起伏，观察水域如何塑造空间。',related:['luoshen','xun','dui']},
 {id:'kun',name:'坤',english:'EARTH · KUN',category:'易象',symbol:'☷',theme:'承载 · 刚柔',subtitle:'至柔之中，也有行动的刚。',intro:'坤关联地与母的意象。承载、生成和行动的力量，构成一个值得重新阅读的空间。',quote:'坤至柔而动也刚，至静而德方。',source:'《周易·坤·文言》',url:'https://ctext.org/book-of-changes/kun/zh',context:'《说卦传》将坤对应地、母。《坤·文言》同时谈柔与刚，也包含妻道、臣道等等级观念。阅读这一传统，需要保留这些张力，不能只截取一句当作现代平等观念的证明。',reading:'今天可以借“承载”讨论支持他人与保持自身结构之间的关系。坤是传统象征，不是女性性格测试；任何人都可以思考它所提出的行动问题。',question:'承载他人时，怎样仍然保有自己的形状？',model:'earth',colors:['#30bcab','#c8d994','#e6b667','#f19dc9','#65b5d8'],action:'展开地层',slider:'地层间距',interaction:'将地层展开，观察每一层的独立结构；合拢时，层与层共同形成一个整体。',related:['nuwa','xuanpin','shouci']},
 {id:'xun',name:'巽',english:'WIND · XUN',category:'易象',symbol:'☴',theme:'风 · 渗入',subtitle:'看不见的风，也改变形状。',intro:'巽在《说卦传》中关联风与长女。风的路径，让不可见的影响有了可观察的痕迹。',quote:'巽为木，为风。',source:'《周易·说卦传》',url:'https://ctext.org/book-of-changes/shuo-gua/zhs',context:'《说卦传》记有巽为木、为风，并以家庭谱系中的长女解释巽。这里的对应属于象征体系；“长女”不等于现代出生顺序心理学，也不能决定现实女性的气质。',reading:'将风转成流线，是我们对不可见作用的现代视觉表达。它可以引出一个问题：影响不总以碰撞的方式发生，缓慢、持续的介入同样会改变局面。',question:'你如何察觉一种尚未显形的影响？',model:'wind',colors:['#40d2b1','#6cafea','#f6a7cc','#e0c264','#9886e9'],action:'改变风向',slider:'风场扭转',interaction:'扭转风场，让几束丝带绕行；模型中的流线是意象演示，不是气象计算。',related:['xiang','luoshen','shouci']},
 {id:'li',name:'离',english:'FIRE · LI',category:'易象',symbol:'☲',theme:'火 · 明',subtitle:'让光，显露内部的层次。',intro:'离关联火、日与中女。我们从明亮与附丽的线索，进入关于观看和关系的讨论。',quote:'离为火，为日，为电，为中女。',source:'《周易·说卦传》',url:'https://ctext.org/book-of-changes/shuo-gua/zhs',context:'《说卦传》列举离与火、日、电、中女等意象的关系。《离》卦的解释还有“丽”的线索。不同取象服务于不同解释，不能把其中一种简化成女性固定的本性。',reading:'光既能照亮，也会制造遮蔽。我们用内外嵌套的曲面，让观看者自己调整明暗，体会显露结构与保留复杂性之间的关系。',question:'被照亮的部分，是否就是全部？',model:'flame',colors:['#ff7da0','#f2be58','#a47af3','#4acdbd','#f7aad5'],action:'点亮内核',slider:'光焰舒展',interaction:'舒展环绕内核的曲面，观察亮面、阴影和空隙之间的变化。',related:['xiwangmu','xuanpin','dui']},
 {id:'dui',name:'兑',english:'LAKE · DUI',category:'易象',symbol:'☱',theme:'泽 · 交流',subtitle:'一次触碰，回应成层层涟漪。',intro:'兑关联泽与少女，也有口舌等取象。水面的回应为交流提供了一种可见的比喻。',quote:'兑为泽，为少女。',source:'《周易·说卦传》',url:'https://ctext.org/book-of-changes/shuo-gua/zhs',context:'《说卦传》把兑与泽、少女、口舌等意象联系起来。这些是古代分类和取象的方法，不是对现实年轻女性应有行为的规定。',reading:'当代设计把泽的波纹用来表达回应与交流。这里的联系是创作选择：允许多个中心同时发出声音，也允许它们相遇而不消失。',question:'交流时，如何让不同的声音都被听见？',model:'water',colors:['#32c8c4','#8bd4ef','#f58dc0','#a99aef','#e2ca77'],action:'发出涟漪',slider:'水面振幅',interaction:'触发波纹，让环形曲面扩展；从上方和侧面观看，会发现不同的结构。',related:['jingwei','xiang','change']},
 {id:'xuanpin',name:'玄牝',english:'THE MYSTERIOUS FEMALE',category:'哲思',symbol:'玄',theme:'空谷 · 生发',subtitle:'空处，也可以成为源头。',intro:'《老子》以玄牝和天地根的意象，讨论持续生成的根源。',quote:'谷神不死，是谓玄牝。玄牝之门，是谓天地根。',source:'《老子》第六章',url:'https://ctext.org/dao-de-jing/zhs',context:'“牝”本指雌性动物，此处参与对“道”的比喻。“玄牝”常被解释为深远、神秘而具有生成能力的根源。它不是一套关于女性身体的现代生理知识。',reading:'把“空”理解为容纳可能性的空间，可以打开新的观察方式。这份智慧并不专属于某一种性别；本专题讨论雌性意象如何参与古典哲学的表达。',question:'如果暂时不把空间填满，什么会发生？',model:'portal',colors:['#bc8dea','#4fd1b6','#f3a7d8','#e9c36a','#73bbee'],action:'打开空谷',slider:'空腔开合',interaction:'打开曲面的内部空腔，观察空处与外部轮廓一起组成形体。',related:['kun','nuwa','shouci']},
 {id:'shouci',name:'守雌',english:'KNOW STRENGTH, KEEP OPENNESS',category:'哲思',symbol:'谿',theme:'柔性 · 处世',subtitle:'力量，也可以有不同姿态。',intro:'“知其雄，守其雌”以相对意象讨论处世，不是要求女性退让的行为守则。',quote:'知其雄，守其雌，为天下谿。',source:'《老子》第二十八章',url:'https://ctext.org/text.pl?if=gb&node=11619&show=parallel',context:'第二十八章把雄与雌、白与黑等意象成对使用，讨论如何保有德、复归于婴儿与朴。其哲学对象并不限于女性，也不能简单译成“女性应当柔弱”。',reading:'这里可以思考：有能力竞争，是否就必须时时竞争？选择开放和低处，可以是一种主动姿态。它不等于在现实伤害中无条件忍耐。',question:'什么时候，改变应对方式也是一种主动？',model:'balance',colors:['#63c5e0','#f59dc6','#8ce0c2','#c0a0ed','#e7c77b'],action:'转换姿态',slider:'双环张力',interaction:'改变双环之间的角度和间距，观察对立的两种姿态如何共享一个空间。',related:['xuanpin','xun','jingwei']}
];
export const categories=['全部','神话人物','易象','哲思'] as const;
export const findEntry=(id:string)=>entries.find(e=>e.id===id);
export const relationships=[
 {a:'nuwa',b:'change',label:'同见《览冥训》',type:'文本关联'},
 {a:'xiwangmu',b:'change',label:'不死之药的叙事',type:'文本关联'},
 {a:'xiwangmu',b:'jingwei',label:'同见《山海经》',type:'文本关联'},
 {a:'kun',b:'xun',label:'《说卦传》取象',type:'文本关联'},
 {a:'xun',b:'li',label:'《说卦传》取象',type:'文本关联'},
 {a:'li',b:'dui',label:'《说卦传》取象',type:'文本关联'},
 {a:'dui',b:'kun',label:'《说卦传》取象',type:'文本关联'},
 {a:'xuanpin',b:'shouci',label:'《老子》的雌性意象',type:'文本关联'},
 {a:'luoshen',b:'xiang',label:'水域中的女性神灵',type:'主题对读'},
 {a:'nuwa',b:'kun',label:'修复与承载',type:'主题对读'},
 {a:'nuwa',b:'jingwei',label:'改变世界的行动',type:'主题对读'},
 {a:'xiang',b:'dui',label:'水域与回应',type:'主题对读'},
 {a:'luoshen',b:'xun',label:'流动的形象',type:'主题对读'},
 {a:'kun',b:'xuanpin',label:'承载与生成',type:'主题对读'},
 {a:'jingwei',b:'shouci',label:'行动姿态的对照',type:'主题对读'},
];
